info:
  app:
    name: Celsius Tracks
    description: iFood Backend Challenge - application to retrieve tracks lists based on the weather
    version: 1.0.0-snapshot

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/celsiustracks
    username: postgres
    password: secretpwd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false


feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #o valor default eh 1000(1s), mas a API do OpenWeather eh meio lenta e estava caindo toda hora no fallback
#            timeoutInMilliseconds: 1 #para teste do fallback (se a API nao responder em 1 milissegundo, cai no fallback)

spotify:
  accessTokenUri: https://accounts.spotify.com/api/token
  username: a68aa3bea6274612b87386d9cd00a007
  password: 1b17a298358744fc9e53c7720dcc145d
  api:
    url: https://api.spotify.com/v1

openweathermap:
  app:
    id: c41fda64c5a62c6a6e0d04876e227a13
  api:
    url: https://api.openweathermap.org/data/2.5